Messages:
  join: '&6Voce entrou na partida $stats'
  stats: '&8(&e$amount&8/&e$max&8)&r'
  permision: '&6você não tem permissão para executar esse comando'
  admin: '&6CampoMinado ADMIN'
  cm: '&8- &a/cm&8 -&7 Abra o menu GUI do evento!'
  cminiciar: '&8- &a/cm iniciar&8 -&7 Inicie o evento!'
  cmsetspawn: '&8- &a/cm setspawn&8 -&7 Sete o inicio do evento!'
  cmsetsaida: '&8- &a/cm setsaida&8 -&7 Sete a saida do evento!'
  spawnsetado: '&6CampoMinado -> setspawn setado com sucesso!'
  saidasetado: '&6CampoMinado -> Saida setada com sucesso!'
  mensagemInicial: '&6&lEvento de CampoMinado aberto. Você tem'
  mensagemFinal: 'segundos.\nPara entrar Digite: &e&l/evento entrar'
  iniciar: '&d&lO evento Campo Minado foi iniciado, boa sorte a todos os jogadores'
  eventoof: '&6ops, não é possivel entrar no evento neste momento'
  entrada: '&6entrou no Servidor'